

DEFAULT_GAME = "hex"
DEFAULT_NUM_GAMES = 1
DEFAULT_HEX_DIM = 5
DEFAULT_P1_AGENT = "user"
DEFAULT_P2_AGENT = "user" 
DEFAULT_P1_AGENT_SAMPLE = True
DEFAULT_P2_AGENT_SAMPLE = True

DEFAULT_RANDOM_FIRST_MOVE = 0.0
DEFAULT_DISPLAY_STATE = False
DEFAULT_LOG_EVERY = 10
DEFAULT_STATES_PER_FILE = 2**20

GAME_OPTIONS = ["tictactoe", "hex"]
AGENT_TYPES = ["nn", "user", "random"]

DEFAULT_BEGIN_FROM = 0
DEFAULT_DATASET_SIZE = 4096
DEFAULT_BATCH_SIZE = 256
DEFAULT_NUM_EPOCHS = 5
DEFAULT_LOG_EVERY_BATCH = 8
DEFAULT_SAVE_EVERY = 1
DEFAULT_LEARNING_RATE = 0.01
DEFAULT_FROM_SCRATCH = True
